<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PB9G11M-LT" ignored="3" name="Xero application test cases" tests="4" failures="1" timestamp="2020-04-05T15:25:37 PDT" time="44.285" errors="0">
  <testcase name="TC_verifyHomePageNextLandingTest" time="2.977" classname="com.xero.TestCases.TestXeroHomePage2"/>
  <testcase name="TC_verifyHomePageTitleTest" time="0.053" classname="com.xero.TestCases.TestXeroHomePage2"/>
  <testcase name="TC_verifyHomePageXeroImgTest" time="1.162" classname="com.xero.TestCases.TestXeroHomePage2"/>
  <testcase name="TC_verifyLoginPageWelcomeMessageTest" time="0.094" classname="com.xero.TestCases.TestXeroLogin">
    <failure type="java.lang.AssertionError" message="expected [Welcome to zero] but found [Welcome to Xero]">
      <![CDATA[java.lang.AssertionError: expected [Welcome to zero] but found [Welcome to Xero]
at com.xero.TestCases.TestXeroLogin.TC_verifyLoginPageWelcomeMessageTest(TestXeroLogin.java:54)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- TC_verifyLoginPageWelcomeMessageTest -->
  <testcase name="TC_verifyLoginCredentialsTest" time="0.0" classname="com.xero.TestCases.TestXeroLogin">
    <ignored/>
  </testcase> <!-- TC_verifyLoginCredentialsTest -->
  <testcase name="TC_verifyLoginPageLogoTest" time="0.0" classname="com.xero.TestCases.TestXeroLogin">
    <ignored/>
  </testcase> <!-- TC_verifyLoginPageLogoTest -->
  <testcase name="@BeforeSuite createReport" time="0.0" classname="com.xero.base.TestXeroBase">
    <ignored/>
  </testcase> <!-- @BeforeSuite createReport -->
</testsuite> <!-- Xero application test cases -->
